package condorcet.Enums;

public enum RequestType {
    REGISTER,
    LOGIN,
    ADD_CLIENT,
    GETALL_DEPOSITS,
    ADD_DEPOSIT,
    GETALL_CARDS,
    GET_CREDITS,
    GETALL_ACCOUNTS,
    AMOUNT_TRANSFER,
    AMOUNT_TRANSFER_CARD_ACCOUNT,
    AMOUNT_TRANSFER_ACCOUNT_CARD,
    AMOUNT_TRANSFER_ACCOUNT_ACCOUNT

}
